
version: "3.7"

services:
  backend:
    container_name: backend
    image: raysandeep/deskaunt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/usr/app
    env_file: .env
    depends_on:
      - redis
    networks:
      - internal
      - web

  backgroundtask:
    build: .
    command: python manage.py process_tasks
    env_file: .env
    networks:
      - internal


networks:
  web:
    external: true
  internal:
    external: false