
version: "3.7"

services:
  backend:
    container_name: backend
    image: raysandeep/deskaunt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/usr/app
    env_file: .env
    depends_on:
      - db
    networks:
      - internal
      - web
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DATABASE}"

  db:
    container_name: db
    image: postgres:10.4
    ports:
      - 5432:5432
    env_file: .env
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  backgroundtask:
    build: .
    command: python manage.py process_tasks
    env_file: .env
    networks:
      - internal
    depends_on: 
      - db
      - backend


networks:
  web:
    external: true
  internal:
    external: false