# Generated by Django 3.0.5 on 2020-05-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritinginputlogger',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
