# Generated by Django 3.0.6 on 2020-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwritinginputlogger',
            name='input_file',
            field=models.FileField(upload_to=''),
        ),
    ]
