# Generated by Django 3.0.5 on 2020-05-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_handwritinginputlogger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritinginputlogger',
            name='error_logger',
            field=models.CharField(default='No error', max_length=100),
        ),
    ]
