# Generated by Django 3.0.6 on 2020-09-22 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handwritinginputlogger',
            name='input_file',
        ),
        migrations.AddField(
            model_name='handwritinginputlogger',
            name='input_file_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
