# Generated by Django 3.0.6 on 2020-09-23 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200922_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='handwritinginputlogger',
            name='input_file_url',
        ),
        migrations.AddField(
            model_name='handwritinginputlogger',
            name='input_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.InputFile'),
            preserve_default=False,
        ),
    ]
