# Generated by Django 3.0.6 on 2020-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200519_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwritinginputlogger',
            name='error_status',
            field=models.BooleanField(default=False),
        ),
    ]
