# Generated by Django 3.0.6 on 2020-05-29 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_handwritinginputlogger_error_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='outputfiles',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
