# Generated by Django 3.0.6 on 2020-05-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200529_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputfiles',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
