# Generated by Django 3.0.6 on 2020-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onesignalnotifications',
            name='player_id',
            field=models.CharField(max_length=400),
        ),
    ]
